services:
  - type: web
    name: hello-work-api
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: "10000"
    autoDeploy: true
